### ISSUE TITLE
Update omniauth from 1.9 for security reasons

### ISSUE THREAD

**Issue by gchapim** [omniauth/omniauth-oauth2#127]
As stated [here](https://nvd.nist.gov/vuln/detail/CVE-2015-9284) omniauth gem versions <= 1.9.0 is vulnerable to Cross-Site Request Forgery when used as part of the Ruby on Rails framework, allowing accounts to be connected without user intent, user interaction, or feedback to the user. This permits a secondary account to be able to sign into the web application as the primary account.

Solution: Update `omniauth` version on gemspec

**Comment by gchapim** [comment]
Waiting for this to be solved https://github.com/omniauth/omniauth/pull/809

**Comment by parasharrk** [comment]
Seems here is the solution https://rubygems.org/gems/omniauth-rails_csrf_protection

**Comment by haizop** [comment]
@gchapim  - Based on reading that thread, it doesn't seem that a fix to the Omniauth gem is necessarily coming anytime soon. The vulnerability is specific to Rails, while Omniauth is not, thus they are having to make decisions about how to deal with supporting platform specific code. That issue has been open for 4 years with no resolution and recently got fresh attention due to github's new security alert.

https://rubygems.org/gems/omniauth-rails_csrf_protection appears to offer a temporary solution.
