### ISSUE TITLE
session being reset during the oauth dance, resulting in `csrf_detected` error

### ISSUE THREAD

**Issue by davetron5000** [omniauth/omniauth-oauth2#183]
While I'm certain I've done something wrong, I cannot figure out what, so I'm asking for any guidance on debugging this behavior.

I'm using the github omniauth plugin, latest versions of everything as of this post.

Here is what is happening:

1. I click a button so my app (sinatra) posts to `/auth/github`
2. Omniauth generates a state value and sends me to GitHub to allow access.
3. I allow access on GitHub
4. When redirected back, a new session is created which thus has no state in it.  The state coming from the GitHub redirect is the state created in step 2.

I cannot figure out when or how the session is being cleared or erased.  This happens in all browsers.  This has worked in the past with this exact app, however I have done gem upgrades and app changes over time.  Again, I'm certain it's something I've done, I just can't figure out how to debug this.

Anyone have any suggestions?

**Comment by davetron5000** [comment]
This is happening on localhost, and it seems that the browser is sending different cookies during the interaction.  A private browser window does not exhibit this behavior.

1. I submit to `/auth/github` and the state is stored in the cookie
2. GitHub redirect includes the state value
3. GitHub authorizes and redirects back with the correct state value
4. When serving the redirect, the browser sends a *different* cookie that does not contain any state value.

It's step 4 that I cannot explain why it is happening, however this all works in a private browser window.  This leads me to believe I have some cookies somewhere that Firefox is sending instead. I have tried clearing cookies for `0.0.0.0` and `localhost` to no avail.

**Comment by jer-k** [comment]
Ran into this myself so I thought I would add some information, hopefully helping the next person. Regular or private window did not matter in my case. 

My use case is as follows

```
# routes.rb
  match(
    "/auth/github",
    to: "oauth/github#passthru",
    as: "user_github_omniauth_authorize",
    via: [:get, :post]
  )
  match(
    "/auth/github/callback",
    to: "oauth/github#callback",
    as: "user_github_omniauth_callback",
    via: [:get, :post]
  )
```

1. User clicks a button to start the OAuth handshake - `<%= button_to 'Connect GitHub Account', user_github_omniauth_authorize_path, data: { turbo: false } %>`
2. User is sent to GitHub, handshake happens, User is redirected back to `/auth/github/callback`
3. I want to prompt User to install GitHub App into their Organization
```ruby
def callback
    ...

    installation_path = "https://github.com/apps/#{github_app_name}/installations/new"
    return redirect_to(installation_path)
end
```
4. User is sent to GitHub, they install the GitHub App, they're redirected back to `/auth/github/callback` and the CSRF happens.

Basically my understanding is that because I'm manually redirecting them back to GitHub instead of OmniAuth doing it, we're losing the request state and `omniauth.state` in the session.

This can be seen in the following logs at that are stopping at this line of code https://github.com/omniauth/omniauth-oauth2/blob/master/lib/omniauth/strategies/oauth2.rb#L86

The first time through (from the initial button click)
```
[1] pry(#<OmniAuth::Strategies::GitHub>)> request.params["state"]
=> "75c2489219fbc66ca52310ecfb3e526f3528f2fc44e81b00"
[2] pry(#<OmniAuth::Strategies::GitHub>)> session["omniauth.state"]
=> "75c2489219fbc66ca52310ecfb3e526f3528f2fc44e81b00"
```

The second time through (from our `redirect_to` call)
```
[1] pry(#<OmniAuth::Strategies::GitHub>)> request.params["state"]
=> nil
[2] pry(#<OmniAuth::Strategies::GitHub>)> session["omniauth.state"]
=> nil
```

This makes sense because OmniAuth had nothing to do with the redirect.

Solution, maintain the state and the session state ourselves

```ruby
def callback
  ...

  request_state = request.params["state"]
  session["omniauth.state"] = request_state
  installation_path = "https://github.com/apps/#{github_app_name}/installations/new?&state=#{request_state}"
  return redirect_to(installation_path)
end
```

Now we're able to confirm that our request state and the session state match.
