### ISSUE TITLE
google_oauth2 Authentication failure! csrf_detected: OmniAuth::Strategies::OAuth2::CallbackError, csrf_detected | CSRF detected

### ISSUE THREAD

**Issue by gdurelle** [omniauth/omniauth-oauth2#58]
Even when creating the state myself it got the same error.

``` ruby
session['omniauth.state'] =  SecureRandom.hex(24)
redirect_to "/auth/google_oauth2?state=#{session['omniauth.state']}"
```

Even though the returned state is the same, meaning it should match !

Isn't there a double redirect or something ? 
Because if so the : 

``` 'ruby
request.params['state'] != session.delete('omniauth.state')
```

in https://github.com/intridea/omniauth-oauth2/blob/master/lib/omniauth/strategies/oauth2.rb#L72 would explain the problem.
=> First passes, second fail.

https://stackoverflow.com/questions/22386149/why-am-i-getting-csrf-detected-with-omniauth-and-google/23739564#23739564

**Comment by danwiding** [comment]
Is this issue related to google issue https://code.google.com/p/gdata-issues/issues/detail?id=6628 wherein occasionally two requests are sent back from google account login?

**Comment by sloptoad** [comment]
where do you put   	provider_ignores_state: true ??

**Comment by mchavarriagam** [comment]
I had to do both for this: remove omniauth.rb initializer (use devise.rb instead) and clearing cookies. I'm using https://github.com/thinkthroughmath/omniauth-clever.

**Comment by jerefrer** [comment]
@valo Thanks for your suggestion. I added this on the `link_to` to prevent users to click multiple times:
`data: { disable_with: '<i class="fa fa-spinner fa-spin" />'}`

**Comment by januszm** [comment]
In my case setting up 'Authorized redirect URIs' at 'https://console.developers.google.com' helped. I've set both production (real domain) and dev urls (localhost:3000)

**Comment by jwg2s** [comment]
Is there a safe version that doesn't suffer from this functionality?  I am experiencing the same thing and have tried provider_ignores_state, domain in session store, and skipping devise authentication for the omniauth controller.  I'm at a loss.

**Comment by Nowaker** [comment]
@jwg2s Please have a look at my PR - that was the reason why I faced this. Maybe your case is very same. https://github.com/zquestz/omniauth-google-oauth2/pull/190/files

**Comment by portOdin** [comment]
When I try to sign in with `http://localhost:3000/auth/github/callback`, I get the `csrf_detected` error. But when I leave out `/callback`, it redirects to Github, but gives a 404. I fixed that by adding `scope: 'user:email'` to the end of the `provider` statement in my `omniauth.rb` initializer. 

Hope that helps.

**Comment by januszm** [comment]
@Nowaker I tried your solution with scope

```ruby
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :google_oauth2, ENV["GOOGLE_CLIENT_ID"], ENV["GOOGLE_CLIENT_SECRET"], scope: 'user:email'
end
```

But then I got

    400. That’s an error.
    Error: invalid_scope
    Some requested scopes were invalid. {invalid=[https://www.googleapis.com/auth/user:email]}

**Comment by Nowaker** [comment]
@januszm In this PR my only point is: when Devise is used, OAuth needs to be configured via Devise, not directly. That's what causes a problem for most people IMO.

You're providing some extra parameters (`scope`) that I've never used and don't know what they're for. You're on your own here. Hope you can figure out what your problem is.

**Comment by januszm** [comment]
Oh that's weird, my comment went to a wrong place. I've just replied using Gmail, sorry I'l remove my message.

**Comment by idrozd** [comment]
Not only two concurrent requests from non-authenticated browser cause two different states;
Second one actually completely overwrites session in browser.

This could happen in case when there is shared Oauth provider (like WSO2 Carbon), and browser is already authenticated in it for some sibling Oauth client site, and then neighbour Oauth client site's two (or more) resources (let's say, two images, or image and banner) are being requested simultaneously (referenced from same page);

If request for first of resources won't finish and set cookie in browser before request for second gets to sibling OAuth client app instance, latter would overwrite session.

Just like @N0hbdy described above.

I haven't found yet a way to mitigate this without leaving only one reference.
Other poor options are dropping "state" param completely,
or hacking into creation of Rack::Session so it would be set unique for unique IP (at least during 2 sec time interval).

**Comment by choonkeat** [comment]
currently we're using the same `session["omniauth.state"]` to store incoming `params[:state]`

``` ruby
# set in authorize_params
session["omniauth.state"] = params[:state]

# checked in callback_phase
request.params["state"] != session.delete("omniauth.state")
```

if we give each state its own namespace, then multiple requests won't trample over each other?
``` ruby
# set in authorize_params
session["omniauth.state.#{params[:state]}"] = params[:state]

# checked in callback_phase
request.params["state"] != session.delete("omniauth.state.#{request.params["state"]}")
```

**Comment by azzy009** [comment]
Help me please to slove the issue of csrf-error Please do tell me urgently..

**Comment by johnnytomcat** [comment]
This is the solution that worked for me.
http://stackoverflow.com/a/25112048

Basically remove omniauth.rb and set you configuration in devise.rb. look for around line 238
```
  # ==> OmniAuth
  # Add a new OmniAuth provider. Check the wiki for more information on setting
  # up on your models and hooks.
  # config.omniauth :github, 'APP_ID', 'APP_SECRET', scope: 'user,public_repo'
  config.omniauth :instagram, ENV['INSTAGRAM_APPID'], ENV['INSTAGRAM_SECRET']
```

**Comment by jwg2s** [comment]
Ours ended up being a race condition where a second request was clearing all the relevant omniauth fields from the session before we'd gotten through the callback phase

**Comment by wazery** [comment]
Guys, can you point us to some steps to solve this issue. I can't figure out what to monkey patch according to @choonkeat solution. I hope if you point out some directions.

**Comment by johnnytomcat** [comment]
@wazery Are you loading a omniauth.rb in you initializers?

**Comment by wazery** [comment]
@johnnytomcat I removed it, and added the following to my devise initializer:

`config.omniauth :github, ENV['github_key'], ENV['github_secret'], { scope: 'email,profile' }`

**Comment by johnnytomcat** [comment]
Have you restarted your webserver process?

**Comment by wazery** [comment]
Sure I did.

**Comment by johnnytomcat** [comment]
Interesting, can you post your stacktrace?

**Comment by wazery** [comment]
Sure, here it's:

```
2016-09-22T04:16:10.588599+00:00 app[web.1]: I, [2016-09-22T04:16:10.588508 #3]  INFO -- : [fa00f0fd-0c13-4491-9de9-9e721463c0e3] Started GET "/auth/github?auth_origin_url=http%3A%2F%2Flocalhost%3A3001%2Flogin&omniauth_window_type=sameWindow" for 41.69.70.119 at 2016-09-22 04:16:10 +0000
2016-09-22T04:16:10.831208+00:00 app[web.1]: I, [2016-09-22T04:16:10.831114 #3]  INFO -- : [92bb6a3c-09df-417d-b1e0-7a9913467d8c] Started GET "/omniauth/github?auth_origin_url=http%3A%2F%2Flocalhost%3A3001%2Flogin&omniauth_window_type=sameWindow&resource_class=User" for 41.69.70.119 at 2016-09-22 04:16:10 +0000
2016-09-22T04:16:10.831563+00:00 app[web.1]: I, [2016-09-22T04:16:10.831508 #3]  INFO -- omniauth: (github) Request phase initiated.
2016-09-22T04:16:10.882031+00:00 heroku[router]: at=info method=GET path="/omniauth/github?auth_origin_url=http%3A%2F%2Flocalhost%3A3001%2Flogin&omniauth_window_type=sameWindow&resource_class=User" host=api.testapp.io request_id=92bb6a3c-09df-417d-b1e0-7a9913467d8c fwd="41.69.70.119" dyno=web.1 connect=1ms service=26ms status=302 bytes=1914
2016-09-22T04:16:11.935466+00:00 app[web.1]: I, [2016-09-22T04:16:11.935387 #3]  INFO -- : [810751e4-63a6-42b4-b5a0-1f294567ec89] Started GET "/omniauth/github/callback?auth_origin_url=http%3A%2F%2Flocalhost%3A3001%2Flogin&code=4ba16a9697e900944ffe&omniauth_window_type=sameWindow&resource_class=User&state=176137e42c90f52350a23cd5c2dc682430521d584c24e2c3" for 41.69.70.119 at 2016-09-22 04:16:11 +0000
2016-09-22T04:16:11.935780+00:00 app[web.1]: I, [2016-09-22T04:16:11.935732 #3]  INFO -- omniauth: (github) Callback phase initiated.
2016-09-22T04:16:11.973638+00:00 app[web.1]: E, [2016-09-22T04:16:11.973547 #3] ERROR -- omniauth: (github) Authentication failure! invalid_credentials: OAuth2::Error, incorrect_client_credentials: The client_id and/or client_secret passed are incorrect.
2016-09-22T04:16:11.973641+00:00 app[web.1]: error=incorrect_client_credentials&error_description=The+client_id+and%2For+client_secret+passed+are+incorrect.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23incorrect-client-credentials
2016-09-22T04:16:11.976290+00:00 app[web.1]: I, [2016-09-22T04:16:11.976216 #3]  INFO -- : [810751e4-63a6-42b4-b5a0-1f294567ec89] Processing by Devise::OmniauthCallbacksController#failure as HTML
2016-09-22T04:16:11.976387+00:00 app[web.1]: I, [2016-09-22T04:16:11.976312 #3]  INFO -- : [810751e4-63a6-42b4-b5a0-1f294567ec89]   Parameters: {"auth_origin_url"=>"http://localhost:3001/login", "code"=>"4ba16a9697e900944ffe", "omniauth_window_type"=>"sameWindow", "resource_class"=>"User", "state"=>"176137e42c90f52350a23cd5c2dc682430521d584c24e2c3"}
2016-09-22T04:16:12.031066+00:00 app[web.1]: I, [2016-09-22T04:16:12.030976 #3]  INFO -- : [810751e4-63a6-42b4-b5a0-1f294567ec89] Redirected to http://api.testapp.io/auth/sign_in
2016-09-22T04:16:12.031266+00:00 app[web.1]: I, [2016-09-22T04:16:12.031218 #3]  INFO -- : [810751e4-63a6-42b4-b5a0-1f294567ec89] Completed 302 Found in 55ms (ActiveRecord: 0.0ms)
2016-09-22T04:16:12.060766+00:00 heroku[router]: at=info method=GET path="/omniauth/github/callback?auth_origin_url=http%3A%2F%2Flocalhost%3A3001%2Flogin&code=4ba16a9697e900944ffe&omniauth_window_type=sameWindow&resource_class=User&state=176137e42c90f52350a23cd5c2dc682430521d584c24e2c3" host=api.testapp.io request_id=810751e4-63a6-42b4-b5a0-1f294567ec89 fwd="41.69.70.119" dyno=web.1 connect=0ms service=101ms status=302 bytes=969
2016-09-22T04:16:12.388728+00:00 heroku[router]: at=info method=GET path="/auth/sign_in" host=api.testapp.io request_id=4c964887-06df-4e45-bd59-5ae1630486c3 fwd="41.69.70.119" dyno=web.1 connect=1ms service=7ms status=405 bytes=413
2016-09-22T04:16:12.355741+00:00 app[web.1]: I, [2016-09-22T04:16:12.355663 #3]  INFO -- : [4c964887-06df-4e45-bd59-5ae1630486c3] Started GET "/auth/sign_in" for 41.69.70.119 at 2016-09-22 04:16:12 +0000
2016-09-22T04:16:12.357932+00:00 app[web.1]: I, [2016-09-22T04:16:12.357870 #3]  INFO -- : [4c964887-06df-4e45-bd59-5ae1630486c3] Processing by DeviseTokenAuth::SessionsController#new as HTML
2016-09-22T04:16:12.360057+00:00 app[web.1]: I, [2016-09-22T04:16:12.359999 #3]  INFO -- : [4c964887-06df-4e45-bd59-5ae1630486c3] Completed 405 Method Not Allowed in 2ms (Views: 0.5ms | ActiveRecord: 0.0ms)
```

**Comment by johnnytomcat** [comment]
I dont see a CSRF error, however i do see 
`2016-09-22T04:16:11.973638+00:00 app[web.1]: E, [2016-09-22T04:16:11.973547 #3] ERROR -- omniauth: (github) Authentication failure! invalid_credentials: OAuth2::Error, incorrect_client_credentials: The client_id and/or client_secret passed are incorrect.`

Can you double check your creds?

**Comment by wazery** [comment]
It's weird that it redirects me to the correct GitHub application, and asks me to authorize, hence the credentials are correct. Weird that this error is in the callback phase.

**Comment by cjbutcher** [comment]
I had a really bad time with this error and wanted to leave a comment to help out anyone in the same situation. I was specifically using an omniauth-github strategy.

In the controller action that renders the view with you auth link on it, include the line:

`session['omniauth.state'] = SecureRandom.hex`

And in the link itself, include that session key as a query parameter called 'state'. I put this method in application helper so I could call it from the view:

```
  def github_auth_url
    "https://github.com/login/oauth/authorize?scope=user:email&client_id=" + Rails.application.secrets.github_client_id + '&state=' + session['omniauth.state']
  end
```

**Comment by marcusmalmberg** [comment]
I also had a problem with this and by chance I found out that visitors using naked domain (non-www) got this error. 

After some digging I found the source to my problem:
- the `callback_url` was set to the www subdomain
- the session_store used default domain settings (which resulted in that different cookies were used for www and naked)
- since the user came from naked domain the session was initiated there, but when the callback came back it was to the www subdomain. Since we didn't have a session we didn't get a match, thus failing.

There are a few different solutions to this:
- Configure session_store to use the same cookie for both naked and www
- Redirect all traffic to either www or naked (and adjust the callback_url to match it)
- Make the callback_url aware of which subdomain should be used

I went with redirecting the traffic to www, since it was better suited for my given situation. There are multiple ways to redirect the traffic, e.g using Rails routes:
```
# config/routes.rb
constraints subdomain: false, domain: 'mydomain.com' do
  get ':any', to: redirect(subdomain: 'www', path: '/%{any}'), any: /.*/
end
```

**Comment by gotno** [comment]
i've been banging my head against this issue for far to long to not leave a comment here letting others know what worked for me.

for context: i'm using oauth within a mounted rails engine. the issue was that the main rails app the engine was mounted in was using https via `force_ssl` but the engine was not. this caused the server to randomly bounce between http and https, which trashed the session and caused the csrf error.

if you're reading this, i hope it helps you to not lose two and a half days to debugging like i did. godspeed!

**Comment by samratjp** [comment]
FWIW, if anyone else comes here with the same issue - I had the same error happen with Hybrid Auth; adding provider_ignores_state in omniauth setup fixed it.

Then another separate bug appeared with invalid_client; which was way more easier to handle - PEBKAC :)

**Comment by gxespino** [comment]
I struggled with this for a few hours and I think I have a decent solution that works for both local development and production.

In my `omniauth.rb` I have:

```ruby
require 'openssl'

config = { }
config = { provider_ignores_state: true } if Rails.env.development?

Rails.application.config.middleware.use OmniAuth::Builder do
  provider(
    :microsoft_v2_auth,
    ENV['CLIENT_ID'],
    ENV['CLIENT_SECRET'],
    config
  )
end
```

In my `session_store.rb` I made sure to declare the domain per the current environment. 

Also, don't forget to clear your cookies upon each attempt to get this to work.

**Comment by eddiej** [comment]
With the hybrid auth approach, it seems that the state is never set locally (usually done at https://github.com/intridea/omniauth-oauth2/blob/master/lib/omniauth/strategies/oauth2.rb#L58). Anyone know if its safe to set `provider_ignores_state` to true if the hybrid approach is used?

**Comment by xiaohui-zhangxh** [comment]
If you got this error with Safari, then try Firefox and Chrome. If only Safari has this issue, then my answer may help, because I spend hours to figure it out.

The problem is, like this URL http://example.org/auth/my-strategy, Safari will send two requests.

The first request to onmiauth, will generate a `state`, then redirect to `my-strategy` login, after login successfully, redirect back to my-strategy callback http://example.org/auth/my-stragegy/callbck with s `state` parameter, at this time Omniauth will compare the `state` value between session and callback parameter.

The second request is going after the first request, it makes Omniauth generate another `state`.

See, the callback `state` param of the first request has not to be the same of `state` in session, that's why we got `CSRF detected` error.

To fix it, I add a timestamp to login URL, http://example.org/auth/my-strategy?t=12345678, Safari won't request this URL twice when I click it.

**Comment by SirRawlins** [comment]
I found this issue myself today, and thanks to @N0hbdy's suggestion. I had a regular AJAX ping going on in the browser which was firing at a similar time as the navigation to the `/auth` path, creating a race condition which was dirtying the session.

Ended up aborting and unbinding the AJAX request on page unload to prevent the race.

**Comment by ginjo** [comment]
@marcusmalmberg , your post solved it for me!

If working with multiple domains, you will have different session cookies. So if you use `callback_url` (or `redirect_uri`), you need to work out your domains/subdomains so that you have a valid session during the callback phase. No more csrf_error 😄 .

**Comment by LiinNs** [comment]
here is my way 
`provider :provider, APP_KEY, APP_SECRET,\
    provider_ignores_state: Rails.env.development?`

**Comment by 0xtobit** [comment]
Changing `localhost` to `127.0.0.1` in my redirect_uri and it was fixed for me.

**Comment by seigel** [comment]
Not sure if this will help anyone, but I had multiple unicorn workers and I believe each one had a different session secret because of me using `SecureRandom.hex` to set them.  I believe if the request came back to a different worker, then I get some weird CSRF token error.  It would work if it hit the same worker.  Using a session value shared between the workers seems to give me better results: `set :sessions, secret: ENV["SESSION_SECRET"]`

I am using Sinatra, and unicorn currently.

**Comment by Randall-Coding** [comment]
I just had the same issue.  Not sure what the state variable has to do with csrf but that is what caused the issue.  

I tried creating the link like so 
google_oath2_calendar_authorize_url (state:{interview_token: token})
which is valid rails syntax I believe, and this caused the error for me.  

Instead creating the link like this worked 
google_oath2_calendar_authorize_url + '?state=' + URI.encode({interview_token: token}.to_json)

**Comment by patrickdavey** [comment]
Unrelated to the above, but, I just ran into this issue and googling brought me here.

My issue was that on `staging` I was using `authenticate_or_request_with_http_basic` as a block for robots etc. if they happen to stumble across our site.

The _weird thing which I don't understand yet_ is that if a user went _directly_ to the url which then issued a redirect to the `auth/provider` endpoint it would ultimately end up with a `csrf_detected` error.

If however the user first went to _any other page_ to get past the `authenticate_or_request_with_http_basic` and _then_ went to the page which did the redirect - it would all work fine.

I don't quite understand why the `authenticate_or_request_with_http_basic` would cause this issue, but, it definitely does for me.

**Comment by dmz006** [comment]
> This problem occurs with rails when the domain defined in `/config/initializer/session_store.rb` is different from the origin/redirect_uri defined in the google api console.
> 
> ```ruby
> MyApp::Application.config.session_store :cookie_store, key: '_app_session', domain: 'my_app.com'
> ```
> 
> Removing the domain params or using the same domain on both sides (plus activating contacts and google+ APIs in console...) fixed the problem for me.
> 
> I think we can close this issue!

Things were working fine for google & facebook but I couldn't get twitter/github or linkedin oauth working.  I found lots of ways people tried to fix this but in the end it was because I had upgraded an old app to rails 5 and the cookie session store that was a default initializer was removed in rails 5 and built into the app.  You can still override it which I think was causing a conflict in the domain used.

If you are running into this problem with an app that was upgraded from 4->5 try commenting out Rails.application.config.session_store in the session_store.rb initializer and see if it helps.

https://github.com/rails/rails/commit/e5a6f7ee9e951dbe0e4e9ea2c0743b4dfb135c57

**Comment by ajeygore** [comment]
> For whatever its worth , I had all these issues because I had my clientId and secret in both my omniauth.rb file as well as my devise.rb config file. I mistakenly did this following the omniauth-google-oauth2 gem instructions. Now I only have the line below in devise.rb.
> config.omniauth :google_oauth2, client, secret
> 
> No omniauth.rb file needed.

That was a saviour, thank you :-) so people who just do google auth with google-omniauth and then change their mind putting devise in mix, will end up in this situation.

**Comment by dwram** [comment]
> For whatever its worth , I had all these issues because I had my clientId and secret in both my omniauth.rb file as well as my devise.rb config file. I mistakenly did this following the omniauth-google-oauth2 gem instructions. Now I only have the line below in devise.rb.
> config.omniauth :google_oauth2, client, secret
> 
> No omniauth.rb file needed.

This resolved it for me!

**Comment by thatguysimon** [comment]
For me the reason this happened was non of the above so I thought I'd share what solved it for me. Maybe it can save someone else a few hours of headaches in the future.

Following [this change](https://blog.chromium.org/2019/10/developers-get-ready-for-new.html) introduced in Google Chrome behavior, we started adding `SameSite=None` to all `Set-Cookie` headers.
But, Chrome also ignores `Set-Cookie` headers that have `SameSite=None` but are missing the `Secure` attribute.
And, since I was running this on localhost, without HTTPS, the `Secure` attribute was not added.

So as a result, my session cookie wouldn't get created on the browser because Chrome would ignore its `Set-Cookie` header, resulting in a new session created on each request, and a failed state comparison.

So if your app is setting `SameSite=None` to all `Set-Cookie` headers, for example with [this gem](https://github.com/github/secure_headers) or [this gem](https://github.com/pschinis/rails_same_site_cookie), and you're getting this error when running locally, you should do **one** of the following:

- In `chrome://flags/`, **disable** "Cookies without SameSite must be secure"

Or 

- Configure your localhost to run in HTTPS.

Hope this helps.

**Comment by FAIZFREADY** [comment]
https://accounts.google.com/o/oauth2/auth/identifier?access_type=online&client_id=651529786092-6c5ahcu0tpp95emiec8uibg11asmk34t.apps.googleusercontent.com&openid.realm=https%3A%2F%2Fwww.openstreetmap.org&redirect_uri=https%3A%2F%2Fwww.openstreetmap.org%2Fauth%2Fgoogle%2Fcallback&response_type=code&scope=email&state=a55bb7c1c493452d2a7060ea22af34bb3a67c4f470ac0124&flowName=GeneralOAuthFlow

**Comment by FAIZFREADY** [comment]
https://www.box.com/legal/privacypolicyhttps://www.box.com/legal/regionalnotice

**Comment by willy-wonka-git** [comment]
Clear coockies helps me

**Comment by gingerlime** [comment]
Having a [similar issue](https://github.com/omniauth/omniauth-oauth2/issues/155) after upgrading to Rails 7, and only with Safari. Firefox/Chrome work fine. Really bizarre. Any tips on how to troubleshoot / fix this?
